services:
  - type: web
    name: arca-backend
    env: docker
    region: singapore
    plan: free
    rootDir: arca-backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SUPABASE_DB_URL
        sync: false
      - key: SUPABASE_PROJECT_URL
        sync: false
      - key: CORS_ALLOWED_ORIGIN
        sync: false
